Service event 支持链式发送
lailongwei/llbc pull request #110
Opened 2023-02-16 10:13 UTC by reckfullol

Service event 支持链式发送

2023-02-16 10:14 UTC, reckfullol commented
Those commits could be squashed  as one if you want.

2023-02-16 11:53 UTC, lailongwei requested changes
辛苦reck，整体没问题，有一个bug跟一些小风格问题：
- 引用计数对象池对象使用有问题，达不到自动释放的目的（这个是否要也可以再商量，可以跟EventManager看齐，就允许泄漏）
- 一些小的风格问题

2023-02-16 11:53 UTC, lailongwei commented on llbc/include/llbc/comm/EventServiceFirer.h
> +class LLBC_EXPORT LLBC_EventServiceFirer : public LLBC_ReferencablePoolObj
命名感觉可以更清晰？LLBC_ServiceEventFirer？

2023-02-16 11:53 UTC, lailongwei commented on llbc/include/llbc/comm/EventServiceFirer.h
> +     * @param[in] ev    - the event object.
'-'前面的空格跟第二个参数未对齐哈

2023-02-16 11:53 UTC, lailongwei commented on llbc/src/comm/EventServiceFirer.cpp
> +// The MIT License (MIT)
reck，我有一个建议：这个cpp代码较简单，是否都不需要这个cpp文件，全部放到inline实现的Inl.h文件中即可？

2023-02-16 11:53 UTC, lailongwei commented on llbc/src/comm/Service.cpp
> +#include "llbc/comm/EventServiceFirer.h"
所有业务头文件在.cpp文件中包含，一定要在`#include "llbc/common/Export.h"`中哈，如果不这样做，会引发符号导出问题，reck，具体可以明天交流下哈

2023-02-16 11:53 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    LLBC_Event *ev = LLBC_GetObjectFromSafetyPool<LLBC_Event>();
此处有小问题：一个对象如果继承`LLBC_ReferencablePoolObj`表示他有引用计数能力，但是业务一样可以让他正常分配跟释放，如果需要获得一个带引用计数的对象，需要调用`LLBC_ObjectPoolInst::GetReferencable<Obj>()`来获得，释放的时候，就这个地方有差别。

2023-02-16 11:53 UTC, lailongwei commented on testsuite/comm/TestCase_Comm_EventInSvc.cpp
> +        svc->BeginFire(TestEvent::TEST_EV_ID3).SetParam("aa", 10086).Fire();
`Chain Call`的代码风格建议多行哈

2023-02-16 11:53 UTC, lailongwei commented on testsuite/core/transcoder/TestCase_Core_Transcoder.cpp
> +    // Test coding string(gbk coding): ???.
这个编码好像又出问题了

2023-02-17 02:00 UTC, lailongwei requested changes
reck，大概review完了哈，此review的comments外，还有两个未在comments中，需要交流下哈：
- EventFirer未运行重用，未重写Clear/clear/Reuse/reuse/Reset/reset之一的方法，需要支持一下，一旦支持了重用，EventFirer的dtor就不再需要任何代码了，因为一定不会到dtor再销毁
- 因为EventFirer包含了LLBC_Event，所以在整个对象池销毁的时候，是有先后顺序的，如果不设置，可能出问题，应该先销毁`EventFirer`的`ObjectPoolInst`，再销毁`Event`的`ObjPoolInst`，这块涉及对象池接口反射，可能需要交流一下才行哈

2023-02-17 02:00 UTC, lailongwei commented on llbc/include/llbc/comm/Service.h
>      virtual LLBC_ObjectPoolInst<LLBC_MessageBlock> &GetMsgBlockObjectPool() = 0;
这个方法是不应该是protected呢？

2023-02-17 02:00 UTC, lailongwei commented on llbc/include/llbc/comm/Service.h
> +    virtual LLBC_ObjectPoolInst<LLBC_ServiceEventFirer> &GetServiceEventFirerObjectPool() = 0;
这个方法是否可以不在`LLBC_Service`中暴露，而只在`LLBC_ServiceImpl`内部实现中定义呢？这边是这样考虑：
* 此方法只有在`LLBC_ServiceImpl::BeginFire()`中被调用, 没有从`LLBC_Service`调用的需求
* 定义在`LLBC_Service`处，多了一个`vptr`的调用开销

2023-02-17 02:00 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +    if(LIKELY(_ev))
如果不从`设计角度`考虑，单纯从`局部代码`角度考虑，需要做防疫式编程，但从`设计角度`来考虑，这个`if (LIKELY(_ev))`应该是不需要的，因为一定不可能为`nullptr`，这边粗看是这样的哈，具体还需要reck你来评估啦

2023-02-17 02:00 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +    if(LIKELY(_ev))
此处的判断跟`SetParam()`一样，感觉可以去除

2023-02-17 02:00 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +}
有这么一个想法，进行代码设计的简化（`对于框架代码，这边的想法是做到：清晰、简洁`，在清晰的前提下，进行简洁化）：
* 可以将此方法删除，因为LLBC_ServiceEventFirer只会由LLBC_ServiceImpl构造，所以可以在构造时就传入ev跟service，完成此方法的一样的功能，且可以省去多一次的变量赋值（构造的时候会初始化一次）
* 从方法必要性角度考虑，确实只需要一个`ctor`即可

---
*PS：`LLBC_EventFirer`可能也有类似的问题，reck可以麻烦一并看下？`

2023-02-17 02:00 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto *eventServiceFirer = static_cast<LLBC_ServiceEventFirer *>(GetServiceEventFirerObjectPool().GetReferencable());
此处可以直接优化成：
`auto *eventServiceFirer = GetServiceEventFirerObjectPool().GetReferencableObject();`

解释：
* 对象池有接口类：`LLBC_IObjectPoolInst`，主要是为了运行时的动态能力（任意类型都可以用统一基类表示），有接口类就意味着需要提供`Get like`方法，所以接口类统一提供两个方法：
  * `void *LLBC_IObjectPoolInst::Get()`：获取一个对象实例，返回`void *`
  * `void *LLBC_IObjectPoolInst::GetReferencable()`：获取一个带引用计划的对象（需要对象继承了`LLBC_ReferencablePoolObj`类），返回`void *`

---
这样一来，基类的`LLBC_IObjectPoolInst`就有了运行时的动态能力，但是每个具体类型的对象池`LLBC_ObjectPoolInst<ObjType>`定义时，额外提供了`GetObject<ObjType>`、`GetReferencableObject<ObjType>`方法，可以让业务知道具体类型的时候，直接调用这两个泛型方法来得到对象，而不用cast，这样有两个好处：
* 代码精简，没有多余的cast及可能的出错
* 省去`vptr`调用开销

2023-02-17 02:00 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto *eventServiceFirer = static_cast<LLBC_ServiceEventFirer *>(GetServiceEventFirerObjectPool().GetReferencable());
此处还有一个问题是：这个对象（`LLBC_ServiceEventFirer`）的引用计数是1，没有标记为`auto release`（类似于obj-c），还是有可能泄漏，所以申请到后，调用一下`LLBC_AutoRelease(eventServiceFirer)`，将其标记为弱引用，这样service在帧尾会进行GC

2023-02-17 02:00 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +        _service = nullptr;
这两个调用可以直接省去，reck，因为已经destruct了哈

2023-02-17 03:46 UTC, lailongwei requested changes
有一些风格问题跟**一个Bug**哈，reck

2023-02-17 03:46 UTC, lailongwei commented on llbc/include/llbc/comm/Service.h
> +    void SetEventInfo(LLBC_ServiceEventFirer *eventServiceFirer, LLBC_Event *ev);
reck，这个好像没有改到，这个应该调整成protected且可调整到`LLBC_ServiceImpl`中

2023-02-17 03:46 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirer.h
> +
多余空行

2023-02-17 03:46 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto *eventServiceFirer = GetServiceEventFirerObjectPool().GetReferencableObject();
有一个小的想法：`LLBC_ServiceEventFirer`对象池不可能被`BeginFire()`之外的其他方法访问，所以可以考虑去除`GetServiceEventFirerObjectPool()`定义，`BeginFire()`方法内直接访问成员，需要reck看下哈

2023-02-17 03:46 UTC, lailongwei commented on testsuite/comm/TestCase_Comm_EventInSvc.cpp
> +
有多余空格
![image](https://user-images.githubusercontent.com/15770958/219543438-c6f969ee-ba9e-4e90-a832-acb3a59136a1.png)

2023-02-17 03:46 UTC, lailongwei commented on testsuite/comm/TestCase_Comm_EventInSvc.cpp
> +
有多余空格
![image](https://user-images.githubusercontent.com/15770958/219543411-ae7e9e2a-fc59-4eb0-9999-cbe834027bc1.png)

2023-02-17 03:46 UTC, lailongwei commented on llbc/include/llbc/comm/Service.h
> +    virtual LLBC_ServiceEventFirer &BeginFire(int eventId) = 0;
`BeginFire()`方法在`LLBC_EventManager`中是能理解的，清晰易懂，在`LLBC_Service`中，可能存在混淆，因为`LLBC_Service`包含了以下主要功能：
- 对象池
- GC池管理
- 事件管理（我们当前优化的）
- 网络及协议栈、订阅相关
- 组件管理

所以是否可以更清晰一些，变成类似`BeginFireEvent()`这样的方法名，虽然长一点，但是链式调用分行后，几乎没有影响，也跟原始的`LLBC_Service::FireEvent()`风格保持一致，具体需要reck你思考后评估哈

2023-02-17 03:46 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +    objPool->AcquireOrderedDeletePoolInst(typeid(LLBC_ServiceEventFirer).name(), typeid(LLBC_ServiceEventFirer).name());
存在Bug，应该是：
```c++
// 告诉LLBC_ObjectPool，在析构时，先删除LLBC_ServiceEventFirer的ObjectPoolInst, 再删除LLBC_Event的ObjectPoolInst
// llbc框架的ObjectPool内部维护的各类型PoolInst的删除依赖树，动态构建，业务通过反射方法OnPoolInstCreate添加自己的依赖要求，框架会动态生成依赖树
objPool->AcquireOrderedDeletePoolInst(typeid(LLBC_ServiceEventFirer).name(), typeid(LLBC_Event).name());
```

2023-02-17 03:46 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +
空行可以删除（感觉）

2023-02-17 03:46 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceEventFirerInl.h
> +}
未来llbc会逐渐c++11->c++14->c++17化，当前可以引入类内定义dtor并` = default`的语法，reck

2023-02-17 04:00 UTC, lailongwei requested changes
最后一个，reck，llbc的目录依赖：common<-core<-comm[unication]<-application

2023-02-17 04:00 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +#include "llbc/core/objectpool/ObjectPoolInst.h"
reck，这个不用包含哈，所有comm/目录的文件，都已经包含过core/的支持的

2023-02-17 05:05 UTC, lailongwei approved these changes

2023-02-17 05:05 UTC, merged