LLBC_Num2Str去除或优化
lailongwei/llbc pull request #164
Opened 2023-05-25 12:18 UTC by reckfullol

2023-05-26 03:52 UTC, lailongwei requested changes
* std::to_string()产生的为std::string类型对象，转换到LLBC_String时会多一层开销，建议还是自己实现num->str的逻辑（参考llbc旧式代码，针对double，可以直接sprintf方式做也可以）
* dec/hex进制，是否可以通过入参带入呢，这样减少一个API？

2023-05-30 03:13 UTC, reckfullol commented
- 已按 msvc stl 的方式实现了基于 num -> char -> llbc string 的转换逻辑, 避免了构建 std::string 产生的冗余开销
- 默认 NumToString 采用 dec, hex 单独实现 NumToStringInHex, 避免函数二义性

2023-05-30 05:27 UTC, lailongwei requested changes
大致看完了哈，reck，有一些疑问跟需要修改的，麻烦你这边看下哈

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    auto val_trunc = unsigned_integral_val;
llbc局部变量当前的命名风格是`小驼峰`，辛苦reck修改下哈

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    }
建议while跟do的结束`}`同行

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +            auto val_trunc = static_cast<unsigned long>(unsigned_integral_val) % 1000000000;
`long`/`unsigned long`在不同平台有不同大小，windows是4bytes，gcc/clang是8bytes，为确保平台可移值性，这里建议调整为`uint32`哈

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    return LLBC_INTERNAL_NS LLBC_IntegralToString(val);
没在上面看到`LLBC_IntegralToString()`函数定义

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    constexpr bool BIG_TYPE = sizeof(unsigned_integral_val) > 4;
BIG_TYPE可以使用enable_if作更进一步的优化哈

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/common/OSHeader.h
> +#include <iomanip>
iomanip在这个地方，好像并没有使用到，是否可以删除？

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +#ifdef _WIN64
llbc有`LLBC_64BIT_PROCESSOR`宏定义，建议使用这个哈，reck
另外这个`_WN64`宏的用意是？没看明白哈

2023-05-30 05:27 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +        while(unsigned_integral_val > 0xFFFFFFFFU)
`0xFFFFFFFU`建议调整为`0xFFFFFFFllu`

2023-05-30 06:17 UTC, reckfullol commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    return LLBC_INTERNAL_NS LLBC_IntegralToString(val);
定义在 129 行

2023-05-31 01:59 UTC, lailongwei requested changes
有一些小的建议跟疑问，辛苦reck再过一遍的

2023-05-31 01:59 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +        *--bufferEnd = static_cast<char>(digit > 9 ? digit - 10 + 'A' : digit + '0');
`digit - 10 + 'A'`中的`10 + 'A'`可优化成一个最终结果，虽然编译器一定会优化，但是从代码层面，能多做一些做一些，可以在优化这块后，注释一个是`10 + 'A'`的优化

2023-05-31 01:59 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    auto valTrunc = unsignedIntegralVal;
这一行copy感觉可以省去

2023-05-31 01:59 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +LLBC_String LLBC_NumToStrInHex(T val)
有一个想法跟一个问题：
想法：泛型方法是否可以直接删除？
问题：是否缺少float/double/long double的实现？

2023-05-31 01:59 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +        bufferEndTrunc = LLBC_UnsignedIntegralToBuffInHex(bufferEndTrunc, typename std::make_unsigned<IT>::type(0 - integralVal));
行长过长，建议调整到100以内哈

2023-05-31 01:59 UTC, lailongwei commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    char *const bufferEnd = std::end(buffer);
`std::end()`实现没有了解过，reck可以辛苦看一下，里面的实现是否比`const * cont bufferEnd = &buffer[21]`高效或者等同哈

2023-05-31 02:06 UTC, reckfullol commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +LLBC_String LLBC_NumToStrInHex(T val)
因为浮点类型无法按照十六进制方式输出, 因此直接使用模板方法

2023-05-31 02:08 UTC, reckfullol commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +    char *const bufferEnd = std::end(buffer);
实现是模板函数萃取出来 buffer 的 SIZE, 返回 buffer + SIZE, 实现效率上等同

2023-05-31 02:41 UTC, reckfullol commented on llbc/include/llbc/core/utils/Util_TextInl.h
> +        *--bufferEnd = static_cast<char>(digit > 9 ? digit - 10 + 'A' : digit + '0');
在不明显影响性能的前提下, `还是想提高代码的可读性`, 避免再用注释去解释代码

2023-05-31 05:10 UTC, lailongwei approved these changes

2023-05-31 05:10 UTC, merged

2023-05-31 05:16 UTC, lailongwei commented
已merged，辛苦reck，额外还有一些疑问跟建议：
- `long`/`ulong`的特化建议调整到`sint64`/`uint64`后面，以更统一
- `InHex函数`实现并没有使用特化来做，而是普通函数，这个是可允许的吗？
- `LLBC_Str2XXX()`也可以一并统一