Use std::mt19937 to replace mt_random.
lailongwei/llbc pull request #221
Opened 2023-09-11 13:59 UTC by lgc1112

Use td::mt19937 to replace mt_random.

2023-09-11 14:06 UTC, lgc1112 commented
At least 1 approving review is required by reviewers with write access.

2023-09-11 14:32 UTC, lailongwei requested changes
建议处理`mtrandom`的min/max的值兼容

2023-09-11 14:32 UTC, lailongwei commented on llbc/include/llbc/core/random/Random.h
> +#include <random>
建议进行优化：
* `#include <random>`放到`OSHeader.h`中（找到合适位置） or 考虑隐藏`std::mt19937`实现（即`RandomInl.h`改名为`Random.cpp`，但会有可能性能损失（call 性能））

2023-09-11 14:32 UTC, lailongwei commented on llbc/include/llbc/core/random/RandomInl.h
> +    _mtRand.seed(seed);
建议查阅api文档，确保Seed()接口跟seed()的参数类型一致

2023-09-11 14:32 UTC, lailongwei commented on llbc/include/llbc/core/random/RandomInl.h
> +        const long long randVal = llabs(static_cast<int>(_mtRand()));
`long long`建议修改为`sint64`，以明确长度

2023-11-25 02:56 UTC, lailongwei requested changes
部分代码可以优化，从**可读性**跟**兼容性**角度

2023-11-25 06:19 UTC, closed without merging