【llbc】EventMgr跟Comp协作增强 #280
lailongwei/llbc pull request #291
Opened 2024-11-19 13:59 UTC by ICLiuLi

2024-11-21 13:04 UTC, lailongwei requested changes
@ICLiuLi 这边想了一下，还是想支持“多EventMgr”联动，因为可以轻松实现，再者：LLBC_Service中的EventMgr是用来做异步、多线程事件传递用的哈，可能也用在游戏线程中不合适，具体可以明天过来探讨下哈

2024-11-21 13:04 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    void RemoveEventListenerStub(const LLBC_Component *comp, _CompRunningPhase phase);
这个属于内部方法，不建议对外暴露哈

2024-11-21 13:04 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    LLBC_Component * _curComp; // Current component.
`_curComp`可以跟上面那一坨定义一起，不需要**孤零零**放着哈

2024-11-21 13:04 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    std::map<std::optional<const LLBC_Component *>, std::map<_CompRunningPhase, std::set<LLBC_ListenerStub>>> _compPhaseListeners; // Component phase listeners.
`std::optional<>`建议去除哈（基于下午企业微信的交流），明天可以再细对下哈

2024-11-21 13:04 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        _curComp = comp;                                                  \
在初始化结束后（不管成功还是失败），建议对_curComp设置null

2024-11-21 13:04 UTC, lailongwei commented on llbc/src/core/event/EventMgr.cpp
> +     static sint64 _maxListenerStub = 1;
多了4个空格

2024-11-21 13:04 UTC, lailongwei commented on llbc/src/core/event/EventMgr.cpp
> +    // LLBC_PrintLn("remove listener event:%d stub:%llu", evId, stub);
测试代码建议直接删除哈

2024-11-25 12:24 UTC, lailongwei requested changes
实际的add/remove操作没再细看啦，等 @ICLiuLi 你这边优化一波后，再继续哈

2024-11-25 12:34 UTC, ICLiuLi commented on llbc/include/llbc/comm/ServiceImpl.h
> +    void AddCollaborateEventMgr(LLBC_EventMgr *evMgr) override;
Collaborative用形容词好了

2024-11-25 12:42 UTC, ICLiuLi commented on llbc/src/core/event/EventMgr.cpp
> +        _evMgrHook->OnEventMgrDestroy(this);
确实，我前面就在想这个问题，拿不定主意，所以前面加了一个map来管理EventMgr到Hook

2024-11-26 02:35 UTC, ICLiuLi commented on llbc/include/llbc/core/event/EventMgr.h
> + class LLBC_EXPORT LLBC_EventMgrHook
- 是否没有必要处理 WillRemove，Service 也是 foreach 调用 RemoveListener 来移除，此时也会调用 WillRemove 会造成迭代器失效，如果不对迭代器操作，也就不需要 WillRemove
- 目前我已经将参数里的 evMgr 移除，改为 Hook 内部保存当前的 evMgr，因为既然都已经绑定了，还每次调用传递一个this，感觉是一个很奇怪的用法，然后在整个管理周期中用到的都是 stub，是否有必要传递和保存 evId

2024-11-26 03:44 UTC, lailongwei requested changes
先进行了EventMgr的review，后面的暂时未review哈，麻烦  @ICLiuLi 再优化一波~

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +     LLBC_EventMgrHook() = delete;
c++标准中：只要有任何的参数构造函数被显式定义，那么默认构造函数就不会自动帮你再实现，所以这个`LLBC_EventMgrHook() = delete;`可以删除哈

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +     LLBC_EventMgrHook(LLBC_EventMgr *evMgr) : _evMgr(evMgr) {}
建议增加`explicit`约束哈

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> + class LLBC_EXPORT LLBC_EventMgrHook
建议补全事件方法定义，增加`OnWillRemoveListener()`

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +     LLBC_EventMgrHook(LLBC_EventMgr *evMgr) : _evMgr(evMgr) {}
参数构造函数有问题：业务直接new一个EventMgrHook即可，不需要有参数，**设置EventMgr到Hook的工作，应该由EventMgrHook提供一个private函数由EventMgr调用，并设置EventMgr为friend class即可**

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +    std::map<LLBC_String, LLBC_EventMgrHook *> _evMgrHook;
建议体现**复数**

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgrInl.h
> +    return LLBC_OK;
从业务代码角度看，以上实现可被接受，从框架角度看，可以继续优化：
### 优化点1：上面有两次map查找，可直接优化成：
```c++
if (!_evMgrHook.insert(name, hook).second)
{
    LLBC_SetLastError(LLBC_ERROR_REPEAT);
    return LLBC_FAILED;
}

return LLBC_OK;
```

### 优化点2：站在这个函数角度，是需要对`hook是否为空`进行校验的，如为空可以选择的错误码建议是：`LLBC_ERROR_ARG`

### 优化点3：if代码块后'}后'建议加一个空行，不建议紧邻，以突出这两块逻辑是：`判断+处理失败`跟`处理成功`的逻辑代码块

2024-11-26 03:44 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgrInl.h
> +    auto *hook = it->second;
建议前面加一个空格，以表示：前面的代码块已经结束，接下来是处理实际移除
同时，llbc规范里面，不会再显式要求“指针一定要加`*`”，所以民可以移除下，保持风格统一就行，在现在ide平台下，加`*`还是稍显冗余，业务代码可以添加，框架代码可以去除哈

2024-11-27 10:00 UTC, ICLiuLi commented on llbc/include/llbc/core/event/EventMgr.h
> + class LLBC_EXPORT LLBC_EventMgrHook
> 建议补全事件方法定义，增加`OnWillRemoveListener()`
是否没有必要处理 WillRemove，Service 也是 foreach 调用 RemoveListener 来移除，此时也会调用 WillRemove 会造成迭代器失效，如果不对迭代器操作，也就不需要 WillRemove
目前我已经将参数里的 evMgr 移除，改为 Hook 内部保存当前的 evMgr，因为既然都已经绑定了，还每次调用传递一个this，感觉是一个很奇怪的用法，然后在整个管理周期中用到的都是 stub，是否有必要传递和保存 evId

2024-11-27 13:27 UTC, lailongwei requested changes
进行了部分查看，有两个大点可能需要讨论：
1. service中对event listener stub的管理信息（`_ManagedStubInfo`）中的阶段，是否应该是Service阶段，因为Service才是核心，Comp受Service管理

2024-11-27 13:27 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +     // Friend class
llbc所有注释要求有`.`结尾（是不是很变态）

2024-11-27 13:27 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +    int AddEventMgrHook(const LLBC_String &name, LLBC_EventMgrHook *hook);
参数`name`类型建议使用`LLBC_CString`，明天过来具体交流下哈

2024-11-27 13:27 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +    void RemoveEventMgrHook(const LLBC_String &name);
同`AddEventMgrHook()`，`name`类型建议使用`LLBC_CString`

2024-11-27 13:27 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +    // Event manager hook
注释要求`.`结尾

2024-11-27 13:27 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgrInl.h
> +    if (hook == nullptr)
llbc框架风格中，不使用啰嗦的` == nullptr`，修改为`!book`即可哈，保持统一

2024-11-27 13:27 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    __LLBC_INL_CHECK_RUNNING_PHASE_EQ(
这个应该不用换行，不会达到120长度

2024-11-27 13:27 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +#define __LLBC_Inl_DestoryComp(comp, destroyMeth, toPhase)          \
这个没看出来修改了啥

2024-11-27 13:27 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    // Before before-stop
注释要求以`.`结束

2024-11-27 13:27 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    RemoveEventListenerStub(nullptr, _CompRunningPhase::LateStarted);
这里有一个疑问：Stop的时候，Service可能处于`LatedStarted`阶段，但是在`LateStart`过程中add的listener是否也应该停止，也即：`StopComps()`中是否应该移除这两个阶段的ListenerStub?

2024-11-27 13:27 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        stubInfo = new _ManagedStubInfo(_curComp->_runningPhase, _curComp, evMgr, stub);
这个running phase，感觉应该用service的，而不是component的？

2024-11-28 02:05 UTC, ICLiuLi commented on llbc/src/comm/ServiceImpl.cpp
> +#define __LLBC_Inl_DestoryComp(comp, destroyMeth, toPhase)          \
> 这个没看出来修改了啥
![image](https://github.com/user-attachments/assets/11f99ec5-b3ce-423d-ad7b-f9d5bdcc4faf)
加了一个RemoveEventListenerStub

2024-11-28 02:07 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +#define __LLBC_Inl_DestoryComp(comp, destroyMeth, toPhase)          \
github对比直接显示一坨有变化

2024-11-28 02:07 UTC, ICLiuLi commented on llbc/src/comm/ServiceImpl.cpp
> +    RemoveEventListenerStub(nullptr, _CompRunningPhase::LateStarted);
> 这里有一个疑问：Stop的时候，Service可能处于`LatedStarted`阶段，但是在`LateStart`过程中add的listener是否也应该停止，也即：`StopComps()`中是否应该移除这两个阶段的ListenerStub?

在 __LLBC_Inl_DestoryComp 的时候做了

2024-11-28 02:09 UTC, ICLiuLi commented on llbc/src/comm/ServiceImpl.cpp
> +        stubInfo = new _ManagedStubInfo(_curComp->_runningPhase, _curComp, evMgr, stub);
> 这个running phase，感觉应该用service的，而不是component的？

因为是跟component状态关联的，还是应该用component的phase吧？

2024-11-28 02:24 UTC, ICLiuLi commented on llbc/src/comm/ServiceImpl.cpp
> +#define __LLBC_Inl_DestoryComp(comp, destroyMeth, toPhase)          \
> github对比直接显示一坨有变化

应该是因为改了\的位置。。。github这个对比有点emmmm

2024-11-28 15:13 UTC, lailongwei requested changes
麻烦再来一版，麻烦 @ICLiuLi

2024-11-28 15:13 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +{
建议实现，用以下方式可规避问题：
remove listener:
case 1: 外部
case 2: 内部
  _removingStub:LLBC_ListenerStub

2024-11-28 15:13 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    class _ManagedStubInfo // Managed event listener stub info
类comment不允许同行注释，需要用`leading comments`，建议：
```c++
// class leading comments
class YourClass {};
```

2024-11-28 15:13 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    };
下面建议加空行

2024-11-28 15:13 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    std::map<LLBC_ListenerStub, _ManagedStubInfo *> _allStubInfos; //  Managed stub info objects
`_allStubInfos`看不出数据结构是什么，也相对不够清晰，建议：
```c++
std::map<LLBC_ListenerStub, _ManagedStubInfo *> _evStub2StubInfos;
```

2024-11-28 15:13 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    std::set<const _ManagedStubInfo *> _runningCompStubInfos; // Stub info is added during the component's running phase.
核心结构建议优化，核心为：
```c++
std::map<LLBC_EventMgr *, std::map<Stub, StubInfo *> > stubInfos;
```

2024-12-01 15:04 UTC, lailongwei requested changes
麻烦 @ICLiuLi 再修正下哈

2024-12-01 15:04 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    return evMgr->AddEventMgrHook(GetName(), new _SvcEvMgrHook(this));
虽然，GetName()不可能重复，但如果外部用了这个Name，那还是有可能重复，此处建议进行必要的错误处理

2024-12-01 15:04 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        RemoveListenerStubByCompAndPhase(comp, _CompRunningPhase::toPhase); \
Destroy component时是往前一个阶段回滚，那么`RemoveListenerStubByCompAndPhase()`调用中的`phase`是否不应该是`toPhase`?

2024-12-02 14:00 UTC, lailongwei requested changes
again

2024-12-02 14:49 UTC, ICLiuLi commented on llbc/src/comm/ServiceImpl.cpp
> +    if (stub2Infos.find(stub) != stub2Infos.end())
是否应该是```stub2Infos.find(stub)== stub2Infos.end()```

2024-12-05 13:16 UTC, lailongwei requested changes
还是需要继续对齐，有一些新的case（较大的设计疏漏）需要讨论，我们都忽略了

2024-12-05 13:16 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto infos = comp2Info.find(info->comp);
变量名`infos`不见名知意，建议有it/iter的前缀（或后缀）

2024-12-05 13:16 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        auto infos = comp2Info.find(stubInfo->comp);
同上，变量名需要体现是iterator

2024-12-05 13:16 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto info = stub2Infos.find(stub);
同上，变量名需要体现是iterator

2024-12-05 13:16 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    for (size_t i = 0; i < stubInfos.size(); ++i)
可以使用泛型for`for (auto &xxx : xxx)`代替

2024-12-05 13:16 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +void LLBC_ServiceImpl::RemoveEventListenerStub(LLBC_EventMgr *evMgr, LLBC_ListenerStub stub)
这个函数有两个地方调用：
- EventMgr销毁的时候
- 组件阶段移除的时候

其中第一个情况下，是不需要再重复调用EventMgr的RemoveListener()的，这里需要看怎么避免

2024-12-05 13:39 UTC, lailongwei requested changes

2024-12-05 13:39 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +
> 这里有几个大漏洞，可能需要讨论一下：
> 
> * 不在Initing（OnInit/OnStart），但Service却在启动中时，可能进入
> * Service Stop后，有add listener操作进来

问题1的解决方案：_curPreparingComp的设置、初始化位置需要缩小
问题2的解决方案Add的时候，如果service阶段不在如下截图范围内，不接受，RemoveListener亦同，EventMgr销毁需要响应

2024-12-12 13:42 UTC, lailongwei requested changes

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    class _SvcEvMgrHook : public LLBC_EventMgrHook // Service event manager hook
类/函数/代码块的注释建议使用`leading comment风格`

2024-12-12 13:42 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +    void OnCollaborativeEventMgrDestroy(llbc::LLBC_EventMgr *evMgr);
命名建议修改，建议：跟`LLBC_EventMgrHook::OnWillRemoveEventMgrHook()`名字保持一致含义

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    RemoveListenerStubByCompAndPhase(nullptr, static_cast<int>(_CompRunningPhase::LateStarted));
放到`2132`行、在`if`语句块中会合适一些？

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    if (_runningPhase < LLBC_ServiceRunningPhase::InitingComps ||
注释一下，合法区间是`[InitingComps, StoppingComps]`

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto curPhase = static_cast<int>(_curPreparingComp ? _curPreparingComp->_runningPhase : _CompRunningPhase::LateStarted);
过长，建议换行
同时建议修改为：`int curPhase = ......`，这样就不必cast了

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    stub2Infos.emplace(stub, stubInfo);
优化点1：
建议先往`stub2Infos`插入，再往辅助的`_phaseCompStubInfos`集合中插入，原因是代码逻辑应该先操作完一个数据结构，再另外一个，而不是分散

优化点2：
容器`stub2Infos`的second可以换成`_ManagedStubInfo`，而不是`pointer`，在此用`emplace`就有价值，否则在这个地方，建议还是用`insert`，还需要看辅助集合`_phaseCompStubInfos`是否可以不存储指针

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    if (_runningPhase < LLBC_ServiceRunningPhase::InitingComps ||
建议注释

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        return;
建议合并成一个`if`，因为这两个条件判断本质是类似的：`过程中不能再移除`

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +
建议删除空格，这块代码是同个逻辑，没必要拆分成两个代码块

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +    auto itStub2Info = _evMgr2StubInfos.find(evMgr);
建议加`leading comment`

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +
建议空格删除

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +
建议空格删除

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        RemoveEventListenerStub(stubInfo->evMgr, stubInfo->stub, false);
建议去除这个调用，会多N次的`_evMgr2StubInfos.find(evMgr)`调用，建议：
在for loop结束后：
```c++
itStub2Info->second.clear();
if (itStub2Info->second.empty())
    _evMgr2StubInfos.erase(itStub2Info);
LLBC_STLHelper::DeleteContainer(stubInfos);

```

2024-12-12 13:42 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        RemoveEventListenerStub(stubInfo->evMgr, stubInfo->stub);
这个方法在上面优化后，只有一处地方有需求，就没有独立一个方法的必要了

2024-12-13 04:13 UTC, lailongwei requested changes
`llbc`core lib剩下最后非常小的`style`类的修改点啦，麻烦 @ICLiuLi 再修改一下
剩下就是`testsuite`工程了，因为当前`Collaborative功能`对应的测试代码还没有异常流程测试，正常流程测试中的event handler也没有对应日志打印，可以完善后再进行次一轮pr？

2024-12-13 04:13 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImpl.h
> +        LLBC_EventMgr * const evMgr;
llbc框架中，const修饰一个const对象指针时，是左侧写的，建议调整为：`const LLBC_Component *`的风格哈

2024-12-13 04:13 UTC, lailongwei commented on llbc/include/llbc/core/event/EventMgr.h
> +private:
这个重复的`private:`可去除

2024-12-13 04:13 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        LLBC_ServiceImpl *_service;
数据成员`_service`命名可统一成`_svc`

2024-12-13 04:13 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
> +        RemoveListenerStubByCompAndPhase(nullptr, static_cast<int>(_CompRunningPhase::LateStarted));
理论上这个`static_cast<int>()`可以省略？可以尝试下

2024-12-13 04:16 UTC, lailongwei requested changes

2024-12-13 04:16 UTC, lailongwei commented on wrap/csllbc/csharp/comm/Service.cs
> +                        throw new LLBCException("Could not repeat set service '{0}' packet exception handler, opcode:{��}, phase: {2}",
这个乱码依然在，比较诡异

2024-12-13 04:16 UTC, lailongwei commented on wrap/csllbc/csharp/comm/Service.cs
> +                        throw new LLBCException("Could not repeat set service '{0}' packet exception handler, opcode:{��}, phase: {2}",
这个也是乱码

2024-12-13 04:16 UTC, lailongwei commented on testsuite/comm/TestCase_Comm_SvcEvStubAutoRemove.h
> +class TestCase_Comm_SvcEvStubAutoRemove : public LLBC_BaseTestCase
testcase的名字是否也叫类似的`Collaborative`之类的会好一些?（容易联想到功能）

2024-12-13 04:16 UTC, lailongwei commented on testsuite/comm/TestCase_Comm_SvcEvStubAutoRemove.cpp
> +        void _OnEv_TestHandle(LLBC_Event &) {}
llbc框架中的`protected`、`private`方法不需要再加`_`，因为是非工程代码

2025-03-11 13:45 UTC, ICLiuLi commented
有一些问题无法通过流程去处理、控制

2025-03-11 13:45 UTC, closed without merging

2025-03-11 13:46 UTC, ICLiuLi commented
> 有一些问题无法通过流程去处理、控制

后续改进优化一下 EventMgrHook