feat: LLBC_Event参数优化
lailongwei/llbc pull request #322
Opened 2024-12-16 08:23 UTC by reckfullol

https://github.com/users/lailongwei/projects/1/views/1?pane=issue&itemId=86682379&issue=lailongwei%7Cllbc%7C285

2024-12-16 10:11 UTC, lailongwei requested changes
主要有两个大修改想法，麻烦reck看下哈：
1. 想去除`int`索引
2. `LLBC_CString`、`std::string`统一成一个（管理层）

2024-12-16 10:11 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    const LLBC_Variant &GetParams(const LLBC_CString &key) const;
函数为获取指定key的值，是否还是单数合适一些？`GetParam()`

2024-12-16 10:11 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    const LLBC_Variant &GetParams(const int &key) const;
之前交流的，好像没有任何必要使用`int`作`event key`，感觉可以直接干掉， @reckfullol 你觉得呢？

2024-12-16 10:11 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    void SetParam(const int &key, const ParamType &param);
同上，这边想去除`int`key参数索引支持

2024-12-16 10:11 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    std::map<std::string, LLBC_Variant> &GetMutableStringKeyParams();
想简化接口，只有一个：`const std::map<LLBC_CString, LLBC_Variant> &GetParams() const`，探讨一下实现哈，下面是这边的思路：
```c++
std::map<LLBC_CString, LLBC_Variant> _params; // 所有params dict
std::unordered_map<const char *, std::string> strKeys; // 针对非CString的key，对应的实际std::string
```

以上做法有两个好处：
1. 整体简化代码，设置的时候，不用再两个map判断是否重复
2. GetParams()接口统一成一个
3. 更主要的：`operator[]`查找操作也变得简单、统一

2024-12-16 10:11 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    std::map<int, LLBC_Variant> &GetMutableIntKeyParams();
`int`key索引想考虑去除，确实没啥需求

2024-12-17 02:19 UTC, lailongwei requested changes
@reckfullol 看了下，整体流程清晰、OK哈，有几个建议哈：
1. 内部概念、命名统一：
   - key分为了`LLBC_CString`及`std::basic_string<>`这两类，我们就统一叫：`slimKey`、`heavyKey`？这样会统一一些，对应参数名信内部成员集合那些可统一概念（以slim、heavy为标准），从设计、概念角度清晰化`LLBC_Event`
2. 代码看下来：`Event.cpp`是不需要存在的了，统一全部在`EventInl.h`中会更简单一些，这边突然的建议哈
3. 在针对`std::basic_string`管理时，存在内存问题，麻烦reck修正下哈
   -

2024-12-17 02:19 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return GetParam(key);
比较好奇，这个地方会定位到`GetParam(LLBC_CString)`版本来调用吗？
另外：是否可以在参数传递处**显式`LLBC_CString(key)`方式来指明调用的`GetParam()`重载版本呢？**

2024-12-17 02:19 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return SetParam(key, LLBC_Variant(param));
同`GetParam`，是否`key`的传递，添加`LLBC_CString()`显式构造，会清晰一些？

2024-12-17 02:19 UTC, lailongwei commented on llbc/src/core/event/Event.cpp
>          it->second = param;
因为**不管如何都要求插入**，故建议简化成：
```c++
_params[key] = param;
```

2024-12-17 02:19 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return SetParam(LLBC_CString(key), LLBC_Variant(param));
`SetParam(std::basic_string<>)`版本方法，有内存问题：
* 内部`LLBC_CString`只是hold住了实参key的`c_str()`，这将导致：调用后的`LLBC_Event`中这个参数`key`野

跟昨天交流的一样哈，建议：
```c++
SetParam(key ,param)
{
    // 构建重度key: heavyKey
    auto heavyKey = new std::string(key.c_str(), key.size());
    // 创建slimKey, 基于heavyKey
    auto slimKey = LLBC_CString(*heavyKey);
    
    // 放入重度key字典
    _heavyKeys.insert(slimKey, heavyKey);
    // 真正set param
    SetParam(slimKey, param);
}
```

Note: 上面示例代码没有考虑key是否重复

2024-12-21 13:58 UTC, lailongwei requested changes
看到一些新的模版编程技巧，可以有！
有一些改进点，麻烦 @reckfullol 改进一波哈

2024-12-21 13:58 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
>  __LLBC_NS_BEGIN
ns定义后，建议留一个空行哈

2024-12-21 13:58 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    if constexpr(LLBC_IsTemplSpec<KeyType, std::basic_string>::value)
`constexpr`后面需要有一个空格

2024-12-21 13:58 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return ;
多余的`return ;`

2024-12-21 13:58 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +std::enable_if_t<LLBC_IsTemplSpec<KeyType, std::basic_string>::value, LLBC_Variant &>
`operator[]`的操作，内部调用`GetParam`、`SetParam`，可不再进行`enable_if`

2024-12-23 01:56 UTC, lailongwei requested changes
整体感觉很简单跟清晰了，剩余一些风格跟细节优化再麻烦reck处理一下哈，感谢reck

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +, _heavyKeys()
非pod类型不需要初始化，可以去除，下面的`_extDataClearDeleg`也麻烦 @reckfullol  顺手去除下哈

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    std::map<LLBC_CString, std::string*> _heavyKeys;
为确保统一，可将`std::string*` -> `std::string *`

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +        _params[heavyIt->first] = std::is_same_v<ParamType, LLBC_Variant> ? param : LLBC_Variant(param);
此处的`?:`三目运算符，也可以变成`if constexpr () {} else {}`格式，以省去一个运行时判断开销，虽然编译器可能会优化，但代码直接直观写出来会更清晰一些

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +        _params[heavyIt->first] = std::is_same_v<ParamType, LLBC_Variant> ? param : LLBC_Variant(param);
不过这个地方的`_params[heavyIt->first] =`其实是内部先construct了再调用`operator =`的，所以感觉可以直接省去`?:`三目运算符？

更进一步探讨：
* 实际使用大部分情况下**不可能对一个已有的key进行replace**
* 在现在的实现中，会永远先`construct`、再`assignment`

故，感觉可以优化成：
```c++
if (not found)
{
    _params.emplace(heavyIt->first, param); // 这里将根据param类型自动匹配variant ctor
}
else
{
    paramIt->second = ...;
}
```

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return clone;
一个crash问题及一个风格问题：
1. Crash问题：
   - clone->_params = _params的时候，会将原来_params中以heavy类型key索引的cstring, copy到clone对象中，当原event对象释放时，去访问clone对象的key，将引发crash
2. 风格问题：
   - llbc中再简单的if/for，代码块，都要求换行哈，有利于阅读，唯一开放的是：代码块如果只有一行，不必再加`{}`

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return const_cast<LLBC_Variant&>(GetParam(key));
在`LLBC_Variant`跟`&`间，要求有`<space>`哈

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    for(auto&[_, heavyKey] : _heavyKeys) delete heavyKey;
同`Clone()`，再简单的`for`/`if`的代码块，都要求换行哈

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    for(auto&[_, heavyKey] : _heavyKeys) delete heavyKey;
另，这个也可以使用`LLBC_STLHelper::DeleteContainer()`完成

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    ClearExtData();
清理的顺序，建议按栈式来，即按变量定义的逆序来处理，像extra data clear delegate，它极有可能还会引用event本身，如果先清理了id跟params，可能引发不必要的问题

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +        (std::is_pointer_v<KeyType> && std::is_same_v<std::remove_cv_t<std::remove_pointer_t<KeyType>>, char>))
提一个优化跟undef配对处理：
* 一个非常小的对齐优化：这两行应该在第一行的`(`内，是否应该多一个空格以**看得出来这两个条件是在第一行的`(`**内的呢？，是一个小细节
* undef配对处理：未看到文件结束（在EventInl.h中）时，对`__LLBC_Inl_EventKeyMatch`进行undef，llbc对临时宏严格遵循：一旦不用，就立刻undef，以免产生不必要的宏污染及编译器的记忆开销，也让代码逻辑更清晰

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    * @param[in] param - the param.
参数名跟描述间的`-`要求对齐

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    std::map<LLBC_CString, std::string*> _heavyKeys;
从“主观感受来看”，`_params`及`_heavyKeys`是`event`主要成员，这边有一个小建议：这两个变量前面的空行可省去，以确保**同个或类似功能数据成员更聚合成一段代码块**

2024-12-23 01:56 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +, _extDataClearDeleg(nullptr) {}
`_extData`及`_extDataClearDeleg`是独立的一块代码块定义，前面可以加一个空行哈
另：在这种情况下的构造函数的函数体建议变成：
```c++
LLBC_Event::LLBC_Event(...)
: ...
, ...
{
}
```

即强制让`{}`独立出两行，因为这时的构造函数已经不是一个简单一行可编写完成的函数，不建议将其**隐藏到同一行中**，麻烦reck

2024-12-23 06:41 UTC, lailongwei requested changes
看到reck将`LLBC_BasicCString`也简化了一下，可以有
还有几个小问题，主要是`SetParam()`上有问题，麻烦reck最后改一波哈

2024-12-23 06:41 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +, _extDataClearDeleg(nullptr)
`_extDataClearDeleg`的初始化，reck可以帮忙移除下哈，因为不需要

2024-12-23 06:41 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    _params[key] = param;
整个`SetParam`函数实现有一些小的问题，感觉如下流程会清晰一些？
```c++
void SetParam(key, param)
{
    // 不管heavy keys中有没有，都进行_params查找，找到更新param并返回
    auto paramIt = _params.find(key);
    if (paramIt != _params.end())
    {
        paramIt->second = param;
        return;
    }

    // 否则走全新添加的流程
    if constexpr (LLBC_IsTemplSpec<KeyType, std::basic_string>::value)
    {
        auto heavyIt = _heavyKeys.find(key);
        if (heavyIt == _heavyKeys.end())
        {
            auto heavyKey = new std::string(key);
            heavyIt = _heavyKeys.insert(std::make_pair(heavyKey->c_str(), heavyKey)).first;
        }

        _params[heavyIt->first] = param;
        // return; // 原代码中这里有return, 不能return，否则下面没有else限制的代码在非std::basic_string spec时也编译
    }
    else
    {
        // else: 直接使用emplace, 内部完成构造
        _params.emplace(key, param);
    }
}
```

2024-12-23 06:41 UTC, lailongwei commented on testsuite/core/event/TestCase_Core_Event.cpp
> +    std::cout << "===================== Test Clone =====================" << std::endl;
当前event testcase用的是 `LLBC_PrintLn()`，为统一，reck也可以用回`LLBC_PrintLn()`哈

2024-12-23 07:09 UTC, reckfullol commented on llbc/include/llbc/core/event/EventInl.h
> +    _params[key] = param;
emplace 的问题是如果已经有 {k, v}, 不会采用新的 v, 因此还是保留使用 operator[]

2024-12-23 08:41 UTC, lailongwei requested changes
看到测试用例也完善了一下，这边额外建的单据到时reck也可以一并关闭了，提交的时候，应该可以关联两个issue
还有最后的几个小优化点，再麻烦reck看一下哈

2024-12-23 08:41 UTC, lailongwei commented on llbc/include/llbc/common/BasicCString.h
> +                         std::is_same_v<std::remove_const_t<std::remove_pointer_t<_Ptr>>, char>, _Ptr>>
`std::is_same_v<...>`属于上面`std::enable_if_t<...`中的&&第后个条件，建议跟第一行的`<`内对齐哈，reck
对比111行你的修改，111行的会更清晰一些：
![image](https://github.com/user-attachments/assets/6a07dfaa-2017-48e6-845a-f511598e13ff)

2024-12-23 08:41 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +         (std::is_pointer_v<KeyType> && std::is_same_v<std::remove_cv_t<std::remove_pointer_t<KeyType>>, char>) \
提一个极限风格优化，具体由reck来选择哈：
- 从代码美观性考虑：4个`||`条件应该从短到长？这个角度我不是很考虑，哈哈，但比当前好
- 从**直观、聚合角度**：是否应该从简单类型判断起，再是复杂类型，即这4个有一定的递进性：
  - `char 数组` -> `char指针` -> `CString` -> `std::basic_string`

具体看reck你的选择哈

2024-12-23 08:41 UTC, lailongwei commented on testsuite/core/event/TestCase_Core_Event.cpp
> +        .SetParam("cstring", "cstring: hello world")
两个同`key`的`param`值，是否本意是想测试覆盖？这里的第二个参数值是否要不一样呢？不太清楚reck你最初的用意哈
下面几个同上哈

2024-12-23 08:41 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +            heavyIt = _heavyKeys.insert(std::make_pair(heavyKey->c_str(), heavyKey)).first;
一个极致优化点：这里的insert可以优化成emplace调用

2024-12-23 08:41 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +        clone->_extDataClearDeleg = new LLBC_Delegate(*_extDataClearDeleg);
这一个`if (...) {}`块跟上面分属两块逻辑，建议加一个空行哈

2024-12-23 08:41 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return clone;
同更，上面添加一个空行

2024-12-23 09:02 UTC, reckfullol commented on testsuite/core/event/TestCase_Core_Event.cpp
> +        .SetParam("cstring", "cstring: hello world")
测试是否会重复添加

2024-12-24 01:52 UTC, lailongwei requested changes
@reckfullol review完哈，有几个点需要再麻烦 @reckfullol 一下：
1. `operator[]`的操作有致命bug（见代码comment），在修正后，也建议编写针对性测试代码验证
2. `Clone()`方法是旧式GC池要求残留，已不再需要，见comment中描述，可替换成对应的`ctors`、`assignments`实现，**同时可以针对性补充这4个`ctors`、`assignments`的测试用例，可以的话，独立一个测试函数专门跑测试**
3. **额外**：有很多需要直接需要流式输出`LLBC_Event`信息，想reck支持一下`std::ostream operator<<(std::ostream &os, const LLBC_Event &event)`支持

2024-12-24 01:52 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return const_cast<LLBC_Variant &>(GetParam(key));
这里会存在一个隐患：**当没有指定key的时候，返回的是static const的variant**，如果业务使用将crash
建议：

2024-12-24 01:52 UTC, lailongwei commented on llbc/include/llbc/core/event/Event.h
> +    LLBC_Event *Clone();
看了一下，`Clone()`方法为历史遗留产物，旧式对象池支持对象池+GC池，有点复杂，GC池的基类是`LLBC_Object`，GC对象建议实现`Clone()`方法，故这里也有`Clone()`实现
麻烦 @reckfullol ：删除`Clone()`方法，增加`copy ctor`、`move ctor`、`copy assignment`、`move assignment`四个方法

2024-12-24 07:04 UTC, lailongwei requested changes
辛苦 @reckfullol  再看一下，还需要一版哈

2024-12-24 07:04 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    "Params:{";
建议做一些对齐哈

2024-12-24 07:04 UTC, lailongwei commented on llbc/include/llbc/core/event/EventInl.h
> +    return o;
最后的`return`前，建议添加空行

2024-12-24 07:04 UTC, lailongwei commented on wrap/pyllbc/src/core/event/_Event.h
> +    auto value = ev->GetParam(evParamKey);
此处应该是`auto &`

2024-12-24 07:04 UTC, lailongwei commented on wrap/pyllbc/src/core/event/_Event.h
> +        return pyllbc_ObjUtil::Variant2Obj(value);
实现有问题：
* get到的变量名是否应该统一成`param`会统一一些？
* get一定会返回，但nil不代表是找不到，业务有可能就是放一个nil key，感觉还是要通过`GetParams().find()`方式并最后判断iter是否为end来判断

2024-12-24 13:26 UTC, reckfullol commented on llbc/include/llbc/core/event/EventInl.h
> +    _extDataClearDeleg = other._extDataClearDeleg;
是指针, 没有拷贝开销

2024-12-24 13:28 UTC, reckfullol commented on llbc/include/llbc/core/event/EventInl.h
> +    _extDataClearDeleg = other._extDataClearDeleg;
同指针拷贝

2024-12-24 14:01 UTC, lailongwei reviewed
@reckfullol `copy ctor`还有一个bug：部分成员未初始化

2024-12-24 14:01 UTC, lailongwei requested changes
@

2024-12-25 01:43 UTC, lailongwei approved these changes

2024-12-25 01:43 UTC, merged