objpool dump format  control
lailongwei/llbc pull request #325
Opened 2024-12-16 13:58 UTC by barton-git

2024-12-17 01:46 UTC, lailongwei requested changes
已简单review，麻烦 @barton-git 再看一下，修正一版哈

2024-12-17 01:46 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +        CSVWithoutHead,
看了下面用法，是通过位方式来确认实际格式，赞！
有个地方可以优化：
* 既然是用位的方式来做，在enum定义的时候，是否应该体现？
  * 哪几位是type？哪几位是type内部的实际定义？一个简单的做法是：[4, 7]位是类型，[0, 3]位是类型内定义
    - `0x00`：Json
    - `0x01`：PrettyJson
    - `0x10`：CSV
    - `0x11`：CSVWithoutHead
 * 在类型说明上，也可以在enum定义处注释清楚

2024-12-17 01:46 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    void SetName(const LLBC_CString& poolName);
`llbc`中`*`跟`&`跟`value`停靠，不是`type`哈，麻烦 @barton-git 修正下的

2024-12-17 01:46 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    LLBC_CString GetName() const;
内部存储其实是`LLBC_String`，其实可以以`LLBC_String`返回哈

2024-12-17 01:46 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    // objpool name default is 'ObjPool_<thread_id>_<safe/unsafe>_<inc-id>'
第一个单词建议大写哈

2024-12-17 01:46 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    _name.format("ObjPool_%d_%s_%d", LLBC_GetCurrentThreadId(), threadSafe ? "safe" : "unsafe", ++id);
看到还是`thread_local`，可以保留，就先这样啦
建议这两行：
* 增加一个必要注释
* 下面空一行，因为跟`Init lock`没有关系，是两个不同代码快

2024-12-17 02:01 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPool.h
> +        CSVWithoutHead,
嗯 好的

2024-12-17 02:01 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    void SetName(const LLBC_CString& poolName);
ok

2024-12-17 02:03 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    // objpool name default is 'ObjPool_<thread_id>_<safe/unsafe>_<inc-id>'
ok

2024-12-17 02:18 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    _name.format("ObjPool_%d_%s_%d", LLBC_GetCurrentThreadId(), threadSafe ? "safe" : "unsafe", ++id);
这里的thread_local我思考了一下，保留的原因主要有2点：1.并不是所有的线程私有变量都有统一创建/删除的需求，这里的id基本可以视作临时变量，使用tls统一控制表有点过重了；2.如果因为添加一个临时的自增量就要依赖libTls模块(这里已经依赖了，只是说这样的场景)，对整体的依赖关系不友好。

2024-12-19 01:56 UTC, lailongwei requested changes
1. 代码细节有待完善的地方，麻烦再处理一遍哈
2. 测试用例未完整体现所有Statistics的测试，未完全测试及覆盖，不可信
3. 测试用例中未看到GetName()/SetName()相关测试，建议：
   - 对objpool name开一个函数独立测试，包括：
     - tls的两个objpools的GetName()测试，是否是正确的名字
     - 自定义objpools的GetName()测试，是否是正确的名字，包括自增id是否有自增
     - 多线程进行thread-safe objpool的  SetName()修改，是否能得到最终的结果以及是否不会crash（这个测试方式可交流）

2024-12-19 01:56 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    LLBC_String _name;
`_name`直观理解来看， 是**核心成员**，可以放到最前面，即在`Thread safe about variables`前面?

2024-12-19 01:56 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    // Init pool name
llbc中的注释统一要求的`.`结尾

2024-12-19 01:56 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    // Objpool name, default is 'ObjPool_<thread_id>_<safe/unsafe>_<inc-id>'
llbc的注释统一要求有`.`结尾

2024-12-19 01:56 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +            // Add headline
统一要求有`.`结尾

2024-12-19 01:56 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +}
函数定义随意了一下，将产生不必要的copy，建议调整为`const LLBC_String &`返回
另：这个函数过于简单，可以在类内直接实现即可

2024-12-19 01:56 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +}
未考虑多线程问题，需要考虑

2024-12-19 03:20 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +}
如果考虑多线程环境这里必须拷贝

2024-12-19 12:02 UTC, closed without merging