tencent/master merge back to llbc master
lailongwei/llbc pull request #329
Opened 2024-12-19 06:35 UTC by barton-git

2024-12-19 12:25 UTC, lailongwei requested changes

2024-12-19 12:25 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +#include "llbc/core/utils/Util_Text.h"
不再需要的头文件

2024-12-19 12:25 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    // Use 4~7 bits as format type, 0~3 bits as specified type
注释要求有结尾句号:`.`

2024-12-19 12:25 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPool.h
> +        CSV = 0x10,
不同类型定义间，可以考虑加空行

2024-12-23 02:42 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    return _name;
2.GetName()使用值返回，函数末尾通过defer释放锁，应该没有多线程的问题，不过其他的建议可接受

2024-12-23 02:44 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    return _name;
”lib用的abi是旧式，带引用计数“，更早期的C++string有copy on write特性，大概c++14之前，后面的版本该特性已经取消

2024-12-23 02:47 UTC, lailongwei commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    return _name;
这块非常有趣，我具体未作测试，因为这里还涉及`RVO`及`NRVO`，有几个点可以face to face交流下：
* 安全问题上，可能需要结合`RVO`这些来讨论，最后到底是defer先还是后？
* abi上，因为现在很多项目其实还是用旧abi，所以会有安全问题哈，我们项目因为很多三方库无法重新编译，所以llbc还是使用旧式abi规范来编译

2024-12-23 02:51 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPool.h
> +    LLBC_String _name;
这里有一点疑问，如何确定一个成员变量是重要的成员，这里我感觉_name反而不如_typedObjPools重要，这里有没有一个确认的标准

2024-12-23 02:59 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +    return LLBC_OK;
这边看了LLBC_Task实现，感觉做了比较重的封装，比如支持继承启动线程，预创建线程内的私有变量，这个对复杂的业务逻辑很有效，但是这里仅希望提供一个执行载体，关注的点在一段相对简单的逻辑，comment提到“为了更强的测试目的”，这边有点没太理解。这边直观的理解是，会不会因为框架有了task实现而尽量避免使用stl的相关实现

2024-12-23 03:00 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.h
> +    int AsyncSetNameTest();
okk

2024-12-23 03:00 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +    LLBC_ReturnIf(AsyncSetNameTest() != LLBC_OK, LLBC_FAILED)
get

2024-12-23 03:00 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPool.h
> +        CSV = 0x10,
ok

2024-12-24 02:03 UTC, lailongwei requested changes
上次的review的一些内容有些未修改，可以详细确认所有comments后再提新pr哈
另外：添加了一些新的comments，麻烦 @barton-git 再确认、修改一下

2024-12-24 02:03 UTC, lailongwei commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +            LLBC_PrintLn("GetName: %s ", _objPool.GetName().c_str());
只是`GetName()`测试，缺少必要的竞态条件，是否这里也是需要进行`SetName()`用?

2024-12-24 02:03 UTC, lailongwei commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +    return LLBC_OK;
return前建议加一行空格，不建议代码完全粘连

2024-12-24 02:03 UTC, lailongwei commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +int TestCase_Core_ObjPool::SafeObjPoolSetNameTest()
整体测试中缺乏最后验证：
* 最后的name应该一定是`xxxxx_99`，即需要看最后的后缀中的数字是否是99

2024-12-24 02:20 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +            LLBC_PrintLn("GetName: %s ", _objPool.GetName().c_str());
SetName在外部线程有调用，2个线程并发执行SetName/GetName实现竞争

2024-12-24 02:21 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +    return LLBC_OK;
ok

2024-12-24 02:22 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +    }
对同一个objpool执行get/set我理解就是竟态，这里感觉不许需要其他的竟态场景

2024-12-24 02:23 UTC, barton-git commented on llbc/include/llbc/core/objpool/ObjPoolInl.h
> +    return retName;
ok

2024-12-24 02:27 UTC, barton-git commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +int TestCase_Core_ObjPool::SafeObjPoolSetNameTest()
get

2024-12-24 12:59 UTC, lailongwei requested changes
只剩下两个非常小的问题，麻烦 @barton-git 快速修改，再提一次pr哈

2024-12-24 13:37 UTC, lailongwei requested changes
![image](https://github.com/user-attachments/assets/a89cb49f-028a-4ef7-9002-5778da6ac820)

2024-12-24 13:37 UTC, lailongwei commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +            LLBC_PrintLn("GetName: %s ", _objPool.GetName().c_str());
`"GetName: %s "`， 多一个后面的无意义的空格

2024-12-24 13:40 UTC, lailongwei approved these changes

2024-12-24 13:40 UTC, lailongwei commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +        else { _SetName(); }
llbc不允许同行`if`、`else`
另：在只有一行时，不需要`{}`

2024-12-24 13:40 UTC, lailongwei commented on testsuite/core/objpool/TestCase_Core_ObjPool.cpp
> +    {}
函数有内容时，{}要求分两行

2024-12-24 13:41 UTC, merged