增加GetCrossedMonths支持
lailongwei/llbc pull request #347
Opened 2024-12-26 12:21 UTC by echo766

增加GetCrossedMonths支持

[issues](https://github.com/lailongwei/llbc/issues/346)

2024-12-27 04:41 UTC, lailongwei requested changes

2024-12-27 04:41 UTC, lailongwei commented on llbc/include/llbc/core/time/TimeInl.h
> +    if (UNLIKELY(diff <= LLBC_TimeSpan::zero))
`GetCrossedMonths()`字面理解就是“跨越了多少个月”，那么：`timeOfMonth`为`0 00:00:00.000000`是否也是合理的？跨越点就是每个月第一天的`00:00:00.000000`？

2024-12-27 04:41 UTC, lailongwei commented on llbc/include/llbc/core/time/TimeInl.h
> +    if (UNLIKELY(timeOfMonth > LLBC_TimeSpan::oneDay*27)) {
跨越了多少个月，timeOfMonth我的理解是：
* 允许的范围是`[0 00:00:00.000000, 30 23:59:59.999999]`，即最大可以到第31天的`23:59:59.999999`
* 如果遇到跨越的月份最大值小于`timeOfMonth`的时候，这个月就按`MIN(timeOfMonth, 本月最后一刻的时刻值)`来计算

按以上两个规则处理后，应该是可以标准化实现？ @echo766

2024-12-27 10:37 UTC, lailongwei requested changes

2024-12-27 10:37 UTC, lailongwei commented on llbc/include/llbc/core/time/Time.h
> +     *        if timeOfMonth=oneDay, it means it's the second day of month.
细心的Note，赞！

2024-12-27 10:37 UTC, lailongwei commented on llbc/include/llbc/core/time/TimeSpan.h
> +    LLBC_TimeSpan AddMicros(sint64 micros) const;
这个原来竟然是`non-const`的...

2024-12-27 10:37 UTC, lailongwei commented on llbc/src/core/time/Time.cpp
> +    }
几个问题哈：
1. 格式不太符合风格哈，建议：
     ```c++
     if (UNLIKELY(timeOfMonth > LLBC_TimeSpan::FromDays(30, 23, 59, 59, 999999L)))
     {
          xxx
     }
2. `FromDays()`使用有问题，原型是：
     ```c++
     LLBC_TimeSpan ::FromDays(int days, int hours, int minutes, int seconds, int millis, int micros)
     ```
3. `FromDays()`参数中的`millis`、`micros`均为`int`，不需要再加`L` suffix哈
     ```
4. 在此处有`ASSERT`，感觉需要跟其它`GetCrossedXXX()`行为一致：作`mod`修正即可，llbc不会在这种“非致命问题”的情况下就直接abort进程，有点过分了，哈哈

一个建议：
1. `FromDays(30, 23, ...)`有点复杂，感觉可以变成`LLBC_TimeSpan::oneDay * 31 - LLBC_TimeSpan::oneMicro`，较清晰？这个我不确定，感觉现在的写法也还行，具体看 @echo766 你哈

2024-12-27 10:37 UTC, lailongwei commented on llbc/src/core/time/Time.cpp
> +    const auto toMaxCycle = LLBC_TimeSpan::FromDays(LLBC_GetMonthMaxDays(to.GetYear(), to.GetMonth()));
有个小问题： `LLBC_Time::GetMonth()`范围是[0, 11]，没错，为了跟`struct tm`一致...所以这里有问题

2024-12-27 10:37 UTC, lailongwei commented on llbc/src/core/time/Time.cpp
> +    return diffYears * 12 + diffMonths;
还没细看算法是否有问题，会继续看，pr先不完成

2024-12-31 04:21 UTC, lailongwei requested changes
完美的算法，有两处小comment，麻烦 @echo766 最后处理下，这边merge哈

2024-12-31 04:21 UTC, lailongwei commented on llbc/src/core/time/Time.cpp
> +    if (UNLIKELY(timeOfMonth >= LLBC_TimeSpan::oneDay*31))
`*`前后麻烦添加` `哈

2024-12-31 04:21 UTC, lailongwei commented on llbc/src/core/time/Time.cpp
> +        const static int daysInMonth[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
可以`constexpr`？

2024-12-31 06:44 UTC, echo766 commented on llbc/src/core/time/Time.cpp
> +        const static int daysInMonth[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
constexpr里面不能有static变量，那需要把dayInMonth放到全局或者是去掉static，感觉意义不大，preMonthMaxDays为static的lambda函数，只会初始化一次，性能上应该也是很好的

2025-01-01 05:07 UTC, lailongwei approved these changes

2025-01-01 05:07 UTC, merged