feat: app 支持 fps #295
lailongwei/llbc pull request #351
Opened 2024-12-30 12:49 UTC by ICLiuLi

2024-12-31 04:36 UTC, lailongwei requested changes
有几处需要麻烦 @ICLiuLi 再优化下的哈

2024-12-31 04:36 UTC, lailongwei commented on llbc/include/llbc/app/App.h
> +    virtual void OnUpdate() {  }
确实可以去除，赞

2024-12-31 04:36 UTC, lailongwei commented on llbc/include/llbc/app/App.h
> +    int SetFPS(int fps);
建议统一成`FPS`

2024-12-31 04:36 UTC, lailongwei commented on llbc/include/llbc/app/App.h
> +    LLBC_SpinLock _fpsLock; // FPS lock.
可以不用lock

2024-12-31 04:36 UTC, lailongwei commented on llbc/include/llbc/app/App.h
> +    sint64 _begRunTime; // Begin heartbeat time, update on every heartbeat begin.
不需要是成员变量，local variable即可？

2024-12-31 04:36 UTC, lailongwei commented on llbc/src/app/App.cpp
> +}
可移入`AppInl.h`中

2024-12-31 04:36 UTC, lailongwei commented on llbc/src/app/App.cpp
> +            (fps < LLBC_CFG_APP_MIN_FPS || fps > LLBC_CFG_APP_MAX_FPS))
llbc if换行加4个spaces或跟`(`对齐即可，暂时未启用8个spaces

2024-12-31 04:36 UTC, lailongwei commented on llbc/src/app/App.cpp
> +    return 1000 / (_fps != static_cast<int>(LLBC_INFINITE) ? _fps : LLBC_CFG_APP_MAX_FPS);
`_fps`为`LLBC_INFINITE`时，`interval`应该是无限趋近于0，感觉返回0合适一些，可再评估下

2024-12-31 04:36 UTC, lailongwei commented on llbc/src/app/App.cpp
> +            LLBC_Sleep(static_cast<int>(GetFrameInterval() - elapsed));
有一个可优化：`GetFrameInterval()`可用`frameInterval`代替

2024-12-31 04:36 UTC, lailongwei commented on llbc/src/app/App.cpp
> +    // - Set application fps
注释需要加`.`结束，另外注释是否统一成`Reload application fps`会合适一些？

2024-12-31 04:36 UTC, lailongwei commented on llbc/src/app/App.cpp
> +            }
可优化成？：
```c++
auto sectionName = cfgItem.first.AsStr().strip().tolower();
if (sectionName != "app" && sectionName != "application")
    break;

// loop and judge cfg key.
// ... ...
```

2024-12-31 04:36 UTC, ICLiuLi commented on llbc/src/app/App.cpp
> +        }
> 感觉这里太啰嗦了，有没有什么简洁一点的写法

NO

2025-01-01 05:09 UTC, lailongwei approved these changes

2025-01-01 05:25 UTC, lailongwei requested changes
还有一些细节需要麻烦 @ICLiuLi 再斟酌一下哈

2025-01-01 05:25 UTC, lailongwei commented on llbc/include/llbc/comm/ServiceImplInl.h
> +    return _fps != static_cast<int>(LLBC_INFINITE) ? 1000 / _fps : 0;
存在多线程问题：访问`_fps`在两个不同的时刻，建议调整为：
```c++
const int fps = _fps;
return ......;
```

2025-01-01 05:25 UTC, lailongwei commented on llbc/src/app/App.cpp
> +    return _fps != static_cast<int>(LLBC_INFINITE) ? 1000 / _fps : 0;
同`LLBC_ServiceImpl::GetFrameInterval()`

2025-01-01 05:25 UTC, lailongwei commented on llbc/src/app/App.cpp
> +    sint64 begRunTime = 0;
一处细节：while中一定会初始化，此处可不初始化，另外，较现代化的写法（不必再遵循旧式c风格写法）是在while (true)内部定义变量即可。

2025-01-01 05:25 UTC, lailongwei commented on llbc/src/app/App.cpp
> +            for (auto cfgSecItem : cfgItem.second.AsDict())
`for`上面建议加一个空行

2025-01-01 05:25 UTC, lailongwei commented on llbc/src/app/App.cpp
> +                    const auto fps = cfgSecItem.second;
这里的`fps`是`LLBC_Variant`类型，可直接删除这一行，在下一行直接进行`SetFPS(cfgSecItem.second)`即可哈

2025-01-01 05:25 UTC, lailongwei commented on llbc/src/app/App.cpp
> +            const auto fps = _cfgType == LLBC_AppConfigType::Xml ? cfgItem.second[LLBC_XMLKeys::Value] : cfgItem.second;
多一次`LLBC_Variant`copy，建议调整为`const auto &`

2025-01-01 05:25 UTC, lailongwei commented on llbc/src/comm/ServiceImpl.cpp
>          sint64 elapsed = LLBC_GetMilliseconds() - _begSvcTime;
未处理elapsed < 0的case，可以帮忙添加处理，直接break即可

2025-01-01 05:25 UTC, lailongwei commented on llbc/include/llbc/app/App.h
> +
`LLBC_App`每个访问域都是一块特定接口集合，`fps相关`的接口有这三个，这些对于`LLBC_App`来说，不是最重要的，同可以放到`Start()`/`Stop()`后面？

2025-01-01 05:25 UTC, lailongwei commented on llbc/include/llbc/app/App.h
> +    volatile int _fps; // App FPS.
`_fps`成员加在这，有点让人感觉是：有一个功能就在后面加一个成员，未考虑**停靠**，个人感觉可以调整到`_name`后面？或者可以再看一下放哪个位置合适哈

2025-01-03 14:18 UTC, lailongwei requested changes

2025-01-03 14:18 UTC, lailongwei commented on llbc/src/app/App.cpp
> +    return LLBC_INL_NS __cfgSuffixes_Unknown;
权衡之下，感觉可恢复旧有代码，因为`if/else if/else if/.../else`块是一个整体，单纯从编译器角度去除`else `会独立本应该属于一块流程判断的逻辑被打断（阅读角度）

2025-01-03 14:18 UTC, lailongwei commented on llbc/src/app/App.cpp
> +
多一个空行

2025-01-03 14:18 UTC, lailongwei commented on llbc/src/app/App.cpp
> +        sint64 begRunTime = LLBC_GetMilliseconds();
下方可多加一行

2025-01-03 14:22 UTC, lailongwei approved these changes

2025-01-03 14:23 UTC, merged