设置service piecetime, os_time支持tsc, cputime linux部分支持tsc
lailongwei/llbc pull request #77
Opened 2022-01-10 06:41 UTC by ericyonng

1.设置service piecetime, os_time支持tsc, cputime linux部分支持tsc  
2.cputime 添加nanoseconds接口,linux初始化频率;

2022-01-11 03:57 UTC, lailongwei requested changes

2022-01-11 03:57 UTC, lailongwei commented on llbc/include/llbc/core/os/OS_TimeImpl.h
> +}
* 对齐问题：建议统一4spaces对齐
* linux侧的获取一秒的频率，建议sleep(1)即可

2022-01-11 03:57 UTC, lailongwei commented on llbc/include/llbc/core/os/OS_TimeImpl.h
> +
* cpuid实现序列化非常低效，建议使用MFENCE;LFENCE;TDTSC完成
* 对齐问题

2022-01-13 07:41 UTC, ericyonng commented on llbc/include/llbc/comm/IService.h
> +
好的

2022-01-13 07:42 UTC, ericyonng commented on llbc/include/llbc/comm/Service.h
> +    uint64 _pieceTime;          // 处理超时时间 linux in nanoseconds, windows in microseconds
好的

2022-01-13 07:42 UTC, ericyonng commented on llbc/include/llbc/common/OSHeader.h
> + #include <intrin.h>
好的

2022-01-13 07:42 UTC, ericyonng commented on llbc/include/llbc/core/os/OS_TimeImpl.h
> +}
好的

2022-01-13 07:43 UTC, ericyonng commented
> 1.设置service piecetime, os_time支持tsc, cputime linux部分支持tsc 2.cputime 添加nanoseconds接口,linux初始化频率;

重新合并

2022-01-13 07:43 UTC, closed without merging