feat: 兼容 mac 和 arm 平台编译
lailongwei/llbc pull request #91
Opened 2022-08-05 15:07 UTC by reckfullol

2022-08-05 15:12 UTC, lailongwei requested changes

2022-08-05 15:12 UTC, lailongwei commented on llbc/include/llbc/core/variant/VariantImpl.h
> +                #endif
```c++
#if LLBC_CUR_COMP == LLBC_COMP_GCC
    return ::std::_Hash_impl::hash(holder.data.raw.doubleVal);
#else // Non-GCC comp
    return std::hash<double>()(holder.data.raw.doubleVal);
#endif
```

2022-08-05 15:14 UTC, reckfullol commented on llbc/include/llbc/core/variant/VariantImpl.h
> +                #endif
Fixed.

2022-08-06 02:39 UTC, lailongwei approved these changes
先通过啦， @reckfullol comment你修改后再提交新的pr哈

2022-08-06 02:39 UTC, lailongwei commented on llbc/include/llbc/core/variant/VariantImpl.h
> +                return LLBC_Hash(nullptr, 0);
此句是否可以再优化成？：
```c++
return (str && !str->empty()) ? LLBC_Hash(str->data(), str->size()) : LLBC_Hash(nullptr, 0);
```

reck可以麻烦看下哈

2022-08-06 02:39 UTC, lailongwei commented on llbc/include/llbc/common/Compiler.h
> + #define LLBC_COMP_VER          (__clang_major__ *10000 + __clang_minor__ *100 + __clang_patchlevel__)
`*10000`跟`*100`可以帮忙增加一个空格

2022-08-06 02:39 UTC, lailongwei commented on llbc/include/llbc/core/os/OS_ThreadImpl.h
> + #elif defined(__x86_64__) || defined(__i386__)
为考虑框架的统一性以及未来架构识别变更的代码最小化修改，reck可以考虑修改成框架内建宏：
* 目标架构宏：`LLBC_TARGET_PROCESSOR`
* 已有架构识别支持：
```c++
// ==================================================================================
// Processer type enumeration.
//
#define LLBC_PROCESSOR_UNKNOWN                              0
#define LLBC_PROCESSOR_X86                                  1
#define LLBC_PROCESSOR_X86_64                               2
#define LLBC_PROCESSOR_ARM                                  3
#define LLBC_PROCESSOR_ARM_THUMB                            4
#define LLBC_PROCESSOR_ARM_64                               5
```

* 识别方法：跟平台类似：
```c++
#if LLBC_TARGET_PROCESSOR == LLBC_PROCESSOR_XXX
// Do some stuff.
#endif // XXX Arch
```

具体可以看此文件：[PFConfig.h](https://github.com/lailongwei/llbc/blob/master/llbc/include/llbc/common/PFConfig.h)

2022-08-06 02:39 UTC, merged